---
- hosts: all
  become: true
  tasks:

  - name: remove repository index
    ansible.builtin.apt:
      update_cache: yes



  - name: intall apache2 package
    ansible.builtin.apt:
      name: apache2
      state: absent

  - name: install support for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: absent

